### PR TITLE
add 3d movements; examples cube and bauble

### PR DESCRIPTION
**Pull request by katjad**
Hi Tom, my first pull request :) 3d works fine now in relatively straightforward cases, but the cube for example does not work if you turn turtle right AND up by say 30 degrees beforehand. It then only moves up all the time when it should be moving down - so I think coords are right for x and z, but not y

### CODE REVIEW

**Comment by tombh** [comment]
Awesome! I'll see if I can get it to run :)

**Comment by katjad** [comment]
Okay :) 

I've since realised that my mental model of how the turtles move and that gets represented by the math is not very satisfactory. The rotating at the moment is by absolute values, so when I say turn right by 30 degrees that means I add 30 degrees to the horizontal angle. But it should really be from the viewpoint of the turtle! 

The best to visualise that is actually with 90 degr turns. Let's say, we start with both angles set to 0, and the turtle is facing in direction of the x axis. If we do 'lean back' by 90 degrees, then move forward, it moves up along the y axis. Then we do a right turn by 90 degrees. This is where it becomes ambiguous! Does it rotate in the vertical plane, next moving along the z axis? Or does it just rotate around its own axis (as if it turned round while 'standing on its hind legs')? In the latter case it would next still move along the y axis (crawling ;) ), and only when you do 'lean forward' by 90 degrees it will _then_ move along the z axis.  - And that latter case is how it works at the moment. It is easier to implement, but much less intuitive. And once you turn the turtle by less then 90 degrees in both directions it becomes very difficult to calculate the rotations you need for drawing a cube for example.

With the more intuitive view, when the turtle turns right by 90 degr in its plane, it's in absolute terms turning by 90 degr _both_ horizontally and vertically. But we also need to know which plane it is in (or in other terms, its rotation around own axis) so we know where it goes when we do 'lean forward' or 'lean back' next! Don't know at the moment if I can extend what I've done so far to switch to this other kind of interpretation or there is a whole different better way of describing which way the turtle is facing after a rotation. Hope I can find out, but cannot do anything before Friday I think. Mmh maybe we do need to go more into vectors!

**Comment by tombh** [comment]
Gosh, I hadn't thought of that. It's hard to visualise isn't it. So let me see if I can describe the issue. Let's say I'm the turtle and I'm standing upright in a Minecraft world and I'm facing a tree straight ahead of me. Now l 'lean back' (BTW I came across another word that might be good: 'tilt') 90 degrees so I'm lying on my back facing the sky with my feet pointing towards the tree. I then move forward rising away from the ground (ie. along the y-axis). Now, the hard bit, I turn right by 90 degrees. What does this mean!?
1. It could mean that my body rotates so that I am always facing the sky but my legs are no longer pointing at the tree, instead, the left side of my body (my left ear if you like) is facing the tree.
2. It could mean that I roll over to the right, as if I was rolling over in bed to get comfy. My legs are still facing the tree.

Personally I feel that 2 is more intuitive, because then there is consistency as to what 'right' does, like flying an aeroplane. Which is what I think you're saying too. But I can see that the maths are more complicated this way.

I can't really even begin to think about how to implement that without getting to know the code better. Once I've got history working and some basic tests we'll be able to develop using Test Driven Development (TDD), which could make things easier. We just need to break the problem down into the smallest possible pieces and test each one :)

**Comment by katjad** [comment]
Yes, I think we mean the same thing ;) It's funny visualising this. Like some Teenage Mutant Ninja Turtle. 'Tilt' is good! Looking forward to the TDD, want to see how that works in Github!

**Comment by katjad** [comment]
ugh running out of time, have to go now. But wanted you to see what I've done. The turnBy() function does not return the correct result yet, but the principle is right. Have not found out exactly what the quat.fromAngleAxis() is doing ("initialising a quat with an angle from an axis" - what does that mean) that is the problem. This is probably the time to write test ;)  -  Also still need to do forward()  - Anyway, quaternions are exciting!

**Comment by katjad** [comment]
It's working!! So happy. It looks very clunky. But it is drawing the right path - so far ;)  In the end I only used the quaternions in the turnBy() function. To instantiate Turtlecraft it is fine to have all three 'states' as vectors (Position, Direction, and left-right Rotation axis - what we called 'facing dir' before). But in turnBy() I think they are essential. Would be so much more difficult with just vectors and matrices or so. Not saying it was easy this way!

Would quite like to try merging, but not now anymore. How does it work? Would I try and merge my branch in my local repository and then push master to remote?

**Comment by tombh** [comment]
Great work! I had a real good look and think about it all last night, but just couldn't figure out how to rotate the direction vector in an axis other than the default quaternion axis.

Though I did come to a similar conclusion about using rotateVec(). From you've done now the only thing I don't understand is what multiplying quaternions does?

I've got a WIP branch where I've already merged your 3d branch into master with some lint fixes too. So I'll make sure the tests pass and push it to this branch :)

**Comment by katjad** [comment]
In these cases, where we essentially multiply two unit vectors perpendicular to each other, you get the cross product, which is a vector perpendicular to both of them (or you could interpret it as deriving the third axis of the turtle's own coordinate system from the other two; which way it's pointing depends on the order in which you multiply). 

Good about the merging. :) Have to try out those tests..

**Comment by tombh** [comment]
Ah! That makes sense. Wow, how do you know that?

**Comment by tombh** [comment]
Yay, tests pass! And I added some more for the tilting movements.

Could you add some more comments walking through what each bit does? It's becoming clearer but I still don't understand some bits.

Also, if you try pulling my latest commit there's a few things to get your head around. You don't have to use Virtualenv but it can help keep pip package versions separate for different projects. You'll need to run `pip install -r requirements` in order for the `nosetests spec/*` command to work. Oh yes, but before that you'll need to use `git submodule init` and then `git submodule update` to install mcpipy and cgkit to their new homes.

Another thing, have a look at [Sublime Linter](http://sublimelinter.readthedocs.org/en/latest/installation.html), it automatically highlights lint errors in python code. It's good way of maintaining good coding practices.

**Comment by katjad** [comment]
Ah great! Have to have a look at all that, will try to get it to work locally. - Yeah will add comments,  think the ones I wrote so far are not always that clear ;)

**Comment by tombh** [comment]
Woah, been having great fun with this! The bauble is amazing! I made a massive spiral out of lava and it seems to have slowed the server down, it is massive!

**Comment by katjad** [comment]
Wow the lava! Saw it all.. ;) Yes, very resource-intensive.

So, I added some comments - possibly too many/long, maybe you can clear some up when you see opportunity? And ha, I removed more quaternions. I realised that for the axis calculation (cross product of perpendicular vectors) you don't really need them, just the vectors. So I used cross product method of the vector class. But the quat for the rotation of dir vector I will hold onto! 
btw quite liked this video explaining them https://www.youtube.com/watch?v=KdW9ALJMk7s Also kind of skim-watched this 4h lecture https://www.youtube.com/watch?v=uRKZnFAR7yw Don't really understand it all, but still fascinating

I seemed to need to put settings.py in the lib directory. It should probably stay at root level? But I did not know how to do that so it would still be imported properly. And why do you take away the options for initialising the Turtlecraft class? I'm sure there is a valid reason, just it seemed to work fine?

So late. Have to leave this all for a few days now. But really glad it is working so well!

**Comment by tombh** [comment]
Thanks for the comments and well done on further simplifying the code by only using one quat! I seem to have simplified the forward() function quite a lot, I can't believe that I've taken out so much code, can you look to see if I've missed something.

Sorry that I keep taking the init vars from Turtlecraft! I did it once as a suggestion then I think I must have taking them away again because the were replaced by a merge conflict, not by you! It was just to avoid the repetition of both classes having the same init vars. It's important.

**Comment by katjad** [comment]
Yay!!!

**Comment by tombh** [comment]
_high five_ :D

**Pull request merged**
